<?php
return $daten = [
    "Aachen" => ["kreis" => "", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Aldenhoven" => ["kreis" => "Düren", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Alfter" => ["kreis" => "Rhein-Sieg-Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Alpen" => ["kreis" => "Wesel", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Alsdorf" => ["kreis" => "Städteregion Aachen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Bad Honnef" => ["kreis" => "Rhein-Sieg-Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Bad Münstereifel" => ["kreis" => "Euskirchen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Baesweiler" => ["kreis" => "Städteregion Aachen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Bedburg" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Bedburg-Hau" => ["kreis" => "Kleve", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Bergheim" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Bergisch Gladbach" => ["kreis" => "Rheinisch-Bergischer Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Bergneustadt" => ["kreis" => "Oberbergischer Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Blankenheim" => ["kreis" => "Euskirchen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Bonn" => ["kreis" => "", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Bornheim" => ["kreis" => "Rhein-Sieg-Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Brüggen" => ["kreis" => "Viersen", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Brühl" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Burscheid" => ["kreis" => "Rheinisch-Bergischer Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Dahlem" => ["kreis" => "Euskirchen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Dinslaken" => ["kreis" => "Wesel", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Dormagen" => ["kreis" => "Rhein-Kreis Neuss", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Duisburg" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Düren" => ["kreis" => "Düren", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Düsseldorf" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Eitorf" => ["kreis" => "Rhein-Sieg-Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Elsdorf" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Emmerich" => ["kreis" => "Kleve", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Engelskirchen" => ["kreis" => "Oberbergischer Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Erftstadt" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Erkelenz" => ["kreis" => "Heinsberg", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Erkrath" => ["kreis" => "Mettmann", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Eschweiler" => ["kreis" => "Städteregion Aachen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Essen" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Euskirchen" => ["kreis" => "Euskirchen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Frechen" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Gangelt" => ["kreis" => "Heinsberg", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Geilenkirchen" => ["kreis" => "Heinsberg", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Geldern" => ["kreis" => "Kleve", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Goch" => ["kreis" => "Kleve", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Grefrath" => ["kreis" => "Viersen", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Grevenbroich" => ["kreis" => "Rhein-Kreis Neuss", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Gummersbach" => ["kreis" => "Oberbergischer Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Haan" => ["kreis" => "Mettmann", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Hamminkeln" => ["kreis" => "Wesel", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Heimbach" => ["kreis" => "Düren", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Heinsberg (Rhld.)" => ["kreis" => "Heinsberg", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Hellenthal" => ["kreis" => "Euskirchen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Hennef (Sieg)" => ["kreis" => "Rhein-Sieg-Kreis", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Herzogenrath" => ["kreis" => "Städteregion Aachen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Hückelhoven" => ["kreis" => "Heinsberg", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Hürtgenwald" => ["kreis" => "Düren", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Hürth" => ["kreis" => "Rhein-Erft-Kreis", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Inden" => ["kreis" => "Düren", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Jülich" => ["kreis" => "Düren", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
    "Köln" => ["kreis" => "", "kennzeichen" => "K", "stelle" => "Z-RGM-Koeln", "email" => "roemisch-germanisches-museum@stadt-koeln.de"],
    "Krefeld" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Leverkusen" => ["kreis" => "", "kennzeichen" => "K", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Mönchengladbach" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Oberhausen" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Solingen" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Wuppertal" => ["kreis" => "", "kennzeichen" => "D", "stelle" => "Overath", "email" => "abr.overath@lvr.de"],
    "Xanten" => ["kreis" => "Wesel", "kennzeichen" => "D", "stelle" => "Xanten", "email" => "abr.xanten@lvr.de"],
    "Zülpich" => ["kreis" => "Euskirchen", "kennzeichen" => "K", "stelle" => "Nideggen", "email" => "abr.nideggen@lvr.de"],
];